### ISSUE TITLE
Bug - Inconsistent Optional Types

### ISSUE THREAD

**Issue by leewardbound** [piercefreeman/mountaineer#100] opened 2024-04-27 23:54 UTC
I'm encountering a weird issue with type generation -

+ I have a "UserPublic" model that gets used in my LayoutContext, which is returned by every Controller in the app, with an optional `email: str | None` type: https://github.com/boundcorp/everest/blob/main/everest/models/detail.py#L47

+ In `models.ts`, the typing result of this output is inconsistent, one has a `?` marking it as optional and the other does not - here's 2 different `models.ts` (from `tables/list/` and `tables/edit/`) side by side -
![image](https://github.com/piercefreeman/mountaineer/assets/395107/de6bf258-7130-4a55-9bf2-9cd8f50f341d)

+ This leads to typing inconsistencies in my LSP, as these are indeed incompatible types -
![image](https://github.com/piercefreeman/mountaineer/assets/395107/ba16f6fb-aee1-430e-875e-394461448a7d)

BUG - I think this is clearly a bug (I've tried deleting the files and regenerating, it still happens), but it also highlights part of an underlying issue - the duplication of types when used on multiple pages.

FEATURE REQUEST - Is it realistic to suggest that someday maybe we could mark a type as "common" (or some similar mechanism) in order to generate a `common_models.ts` file, sharing types that are used repeatedly? My application uses this LayoutContext on every page, it seems like this will be a common pattern for advanced frontends -
https://github.com/boundcorp/everest/blob/main/everest/core/layout.py#L21

**Comment by piercefreeman** [comment] 2024-04-29 05:55
Agreed this is a bug. I suspect there's some internal conflict in `convert_schema_to_typescript` (https://github.com/piercefreeman/mountaineer/blob/cf7073366d6dc3e69ccd1914e0a7edbf71674770/mountaineer/client_builder/builder.py#L138) where it's enforcing the required payloads for some render endpoints but not others. I'll look into this and put up a fix in the next couple of days.

After the conversation in https://github.com/piercefreeman/mountaineer/issues/47, I believe layout controllers are the best solution here. It would remove the need for you to pass a `UserPublic` model to all controllers, if you are able to encapsulate the UI in a single layout state. If you have multiple prototypical layouts, you could consolidate them to a few different layouts. General purpose global state is a risky proposition for a host of reasons (relative import paths and naming conflicts across controller files are the main ones). I don't imagine Mountaineer will ever support that, or at least no time soon.

**Comment by piercefreeman** [comment] 2024-05-01 13:38
Indeed, I do believe the root cause here is the logic in convert_schema_to_typescript.

```python
class UserBase(BaseModel):
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    username: str
    email: str | None = None
    is_verified: bool = False
    is_staff: bool = False
    is_superuser: bool = False
    last_login: Optional[datetime] = Field(
        sa_column=Column(
            DateTime,
            nullable=True,
        )
    )
```

In your `UserBase` model the fields with default values are being marked as optional. We _want_ this to happen to action arguments, because you don't have to set these values on the client. But we don't want them to happen on server returned values since we're guaranteed to always have a value set when it's serialized into JSON.

The actual specifics here were a bit different than my original hypothesis. The code in question:

```python
@sideeffect
async def partial_update(self, update: AdminTableRow,
session: AsyncSession = Depends(DatabaseDependencies.get_db_session),
layout: LayoutContext = Depends(LayoutContext.get_item_layout)
) -> None:
```

Here you're using a `LayoutContext` BaseModel wrapper to store your internal server-side arguments. This should be totally valid, but isn't a case that we have captured. I believe Mountaineer is identifying this as a BaseModel within a `@sideeffect` signature and going ahead and exporting the model as an optional client type in case the client wants to send an argument server-side. This doesn't actually work in practice, of course, but seems to be where this bug is coming from.

The only "layout" that we should be sending down to the client is in the `render` itself which should be fully populated at json serialize time and therefore have fully filled arguments.

**Comment by leewardbound** [comment] 2024-05-05 20:26
Thanks Pierce, that makes sense! I appreciate your inspecing my code and figuring out where my usage was unsupported, I'll adjust accordingly (either by adjusting my backend types or by adding `Required<T>` to my frontend action-based types).

On the topic of "Duplicate Code / Common Modules" - I've reflected on it a bit and decided I actually prefer the current implementation, over my previous suggestion. I think it's lightweight, a lot cleaner, and helps avoid producing large or complex bundles. The "duplicate code" is all generated build output, it's a feature-not-a-bug, I like it.

Some feedback Re: LayoutControllers - I'm playing with 0.5.0-dev2 today and shifting bits around trying to find a solution I like for my app. Ultimately I might not use it in it's current state... My current `LayoutContext.get_layout()` dependency, which I inject in every view, is working great for my needs - it retrieves the User, and optionally the Table and the Item (table row) - and it's leveraging query parameters (which LayoutContext doesn't support); I use the query parameters to determine which Table and which Item we are viewing, and these values will be needed in the react LayoutComponent to render the navbar correctly. I think that having QPs modify the navbar UI is a pretty common pattern in frontends.

I'm new to dependency injection and FastAPI alike, so I don't know if this is a viable suggestion, or a "good" direction for DX in your framework, but what are your thoughts on adding query parameter support to LayoutControllers, with the condition that all parameters must have default values? This would let me use the LayoutController as I currently use it now - some pages have `{table_id}/` in the path, and some have `{table_id}/{item_id}` but they all use the same Dependency together since the values are optional.

We can close this ticket any time, the original bug is my fault :)

**Comment by piercefreeman** [comment] 2024-05-07 23:16
> I don't know if this is a viable suggestion, or a "good" direction for DX in your framework, but what are your thoughts on adding query parameter support to LayoutControllers, with the condition that all parameters must have default values?

A good direction of DX certainly. I just put up https://github.com/piercefreeman/mountaineer/pull/109, which should accomplish full feature parity between layout controllers and page controllers. Query parameters can have optional defaults or required ones, up to you. It needs some more tests then will merge in.

**Comment by leewardbound** [comment] 2024-05-08 16:18
incredible man, you are a powerhouse! i'm still having lots of fun working in mountaineer, thanks for all you do!

**Closed** 2024-05-13 17:52 UTC
